module.exports = {

  /* ETC */
  OK: "성공",
  NULL_VALUE: "필요한 값이 없습니다",
  OUT_OF_VALUE: "파라미터 값이 잘못 되었습니다.",
  INTERNAL_SERVER_ERROR: "서버 내부 오류",
  NEED_LOGIN: "로그인 필요",
  CANT_ACCESS: "접근할 수 없습니다",

  /* City */
  CITY_EMPTY: "도시가 없습니다",
  CITY_READ_ALL_SUCCESS: "도시 전체 조회 성공",
  CITY_READ_ALL_FAIL: "도시 전체 조회 실패",
  CITY_READ_COUNTRY_SUCCESS: "해당 국가 도시 조회 성공",
  CITY_READ_COUNTRY_FAIL: "해당 국가 도시 조회 실패",
  CITY_CREAT_FAIL: "CITY 제작 실패",
  CITY_CREAT_SUCCESS: "CITY 제작 성공",
  CITY_UPDATE_FAIL: "CITY UPDATE 실패",
  CITY_UPDATE_SUCCESS: "CITY UPDATE 성공",
  CITY_DELETE_FAIL: "CITY DELETE 실패",
  CITY_DELETE_SUCCESS: "CITY DELETE 성공",

  /* Timeline */
  TIMELINE_EMPTY : "지출내역이 없습니다.",
  TIMELINE_READ_SUCCESS : "지출내역 조회 성공", 
  TIMELINE_READ_FAIL : "지출내역 조회 실패", 
  TIMELINE_CREATE_SUCCESS : "지출내역 추가 성공",
  TIMELINE_CREATE_FAIL : "지출내역 추가 실패",
  TIMELINE_UPDATE_SUCCESS : "지출내역 수정 성공",
  TIMELINE_UPDATE_FAIL : "지출내역 수정 실패",
  TIMELINE_DELETE_SUCCESS : "지출내역 삭제 성공",
  TIMELINE_DELETE_FAIL : "지출내역 삭제 실패",

  /* Activity */
  ACTIVITY_READ_CITYID_FAIL: "CityId에 해당하는 Activity 조회 실패",
  ACTIVITY_READ_CITYID_SUCCESS: "CityId 해당하는 Activity 조회 성공",
  ACTIVITY_CREAT_FAIL: "ACTIVITY 제작 실패",
  ACTIVITY_CREAT_SUCCESS: "ACTIVITY 제작 성공",
  ACTIVITY_UPDATE_FAIL: "ACTIVITY UPDATE 실패",
  ACTIVITY_UPDATE_SUCCESS: "ACTIVITY UPDATE 성공",
  ACTIVITY_DELETE_FAIL: "ACTIVITY DELETE 실패",
  ACTIVITY_DELETE_SUCCESS: "ACTIVITY DELETE 성공",
  ACTIVITY_EMPTY: "ACTIVITY가 없습니다",


  /* Food */
  FOOD_READ_CITYID_FAIL: "CityId에 해당하는 FOOD 조회 실패",
  FOOD_READ_CITYID_SUCCESS: "CityId 해당하는 FOOD 조회 성공",
  FOOD_CREAT_FAIL: "FOOD 제작 실패",
  FOOD_CREAT_SUCCESS: "FOOD 제작 성공",
  FOOD_UPDATE_FAIL: "FOOD UPDATE 실패",
  FOOD_UPDATE_SUCCESS: "FOOD UPDATE 성공",
  FOOD_DELETE_FAIL: "FOOD DELETE 실패",
  FOOD_DELETE_SUCCESS: "FOOD DELETE 성공",
  FOOD_EMPTY: "FOOD가 없습니다",

  /* Hotel */
  HOTEL_READ_CITYID_FAIL: "CityId에 해당하는 HOTEL 조회 실패",
  HOTEL_READ_CITYID_SUCCESS: "CityId 해당하는 HOTEL 조회 성공",
  HOTEL_CREAT_FAIL: "HOTEL 제작 실패",
  HOTEL_CREAT_SUCCESS: "HOTEL 제작 성공",
  HOTEL_UPDATE_FAIL: "HOTEL UPDATE 실패",
  HOTEL_UPDATE_SUCCESS: "HOTEL UPDATE 성공",
  HOTEL_DELETE_FAIL: "HOTEL DELETE 실패",
  HOTEL_DELETE_SUCCESS: "HOTEL DELETE 성공",
  HOTEL_EMPTY: "HOTEL가 없습니다",

  /* Shopping */
  SHOPPING_READ_CITYID_FAIL: "CityId에 해당하는 SHOPPING 조회 실패",
  SHOPPING_READ_CITYID_SUCCESS: "CityId 해당하는 SHOPPING 조회 성공",
  SHOPPING_CREAT_FAIL: "SHOPPING 제작 실패",
  SHOPPING_CREAT_SUCCESS: "SHOPPING 제작 성공",
  SHOPPING_UPDATE_FAIL: "SHOPPING UPDATE 실패",
  SHOPPING_UPDATE_SUCCESS: "SHOPPING UPDATE 성공",
  SHOPPING_DELETE_FAIL: "SHOPPING DELETE 실패",
  SHOPPING_DELETE_SUCCESS: "SHOPPING DELETE 성공",
  SHOPPING_EMPTY: "SHOPPING가 없습니다",

  /* Snack */
  SNACK_READ_CITYID_FAIL: "CityId에 해당하는 SNACK 조회 실패",
  SNACK_READ_CITYID_SUCCESS: "CityId 해당하는 SNACK 조회 성공",
  SNACK_CREAT_FAIL: "SNACK 제작 실패",
  SNACK_CREAT_SUCCESS: "SNACK 제작 성공",
  SNACK_UPDATE_FAIL: "SNACK UPDATE 실패",
  SNACK_UPDATE_SUCCESS: "SNACK UPDATE 성공",
  SNACK_DELETE_FAIL: "SNACK DELETE 실패",
  SNACK_DELETE_SUCCESS: "SNACK DELETE 성공",
  SNACK_EMPTY: "SNACK가 없습니다",

  /* Transport */
  TRANSPORT_READ_CITYID_FAIL: "CityId에 해당하는 TRANSPORT 조회 실패",
  TRANSPORT_READ_CITYID_SUCCESS: "CityId 해당하는 TRANSPORT 조회 성공",
  TRANSPORT_CREAT_FAIL: "TRANSPORT 제작 실패",
  TRANSPORT_CREAT_SUCCESS: "TRANSPORT 제작 성공",
  TRANSPORT_UPDATE_FAIL: "TRANSPORTAT UPDATE 실패",
  TRANSPORT_UPDATE_SUCCESS: "TRANSPORT UPDATE 성공",
  TRANSPORT_DELETE_FAIL: "TRANSPORT DELETE 실패",
  TRANSPORT_DELETE_SUCCESS: "TRANSPORT DELETE 성공",
  TRANSPORT_EMPTY: "TRANSPORT가 없습니다",

  /* Schedule */
  SCHEDULE_READ_ALL_SUCCESS: "일정 전체 조회 성공",
  SCHEDULE_READ_ALL_FAIL: "일정 전체 조회 실패",
  SCHEDULE_READ_TRIPID_SUCCESS: "TRIP ID로 일정 조회 성공",
  SCHEDULE_READ_TRIPID_FAIL: "TRIP ID로 일정 조회 실패",
  SCHEDULE_READ_DAY_SUCCESS: "DAY로 일정 조회 성공",
  SCHEDULE_READ_DAY_FAIL: "DAY로 일정 조회 실패",
  SCHEDULE_CREATE_SUCCESS: "일정 제작 성공",
  SCHEDULE_CREATE_FAIL: "일정 제작 실패",
  SCHEDULE_DELETE_SUCCESS: "일정 삭제 성공",
  SCHEDULE_DELETE_FAIL: "일정 삭제 실패",
  ALREADY_SCHEDULE: "일정이 존재합니다.",
  SCHEDULE_EMPTY: "일정이 비어있습니다",

  /* Trip */
  TRIP_READ_SUCCESS: "TRIP ID로 조회 성공",
  TRIP_READ_FAIL: "TRIP ID로 조회 실패",
  TRIP_LIST_READ_SUCCESS: "TRIP 후보 조회 성공",
  TRIP_LIST_READ_FAIL: "TRIP 후보 조회 실패",
  TRIPPING_READ_SUCCESS: "여행 중인 TRIP 조회 성공",
  TRIPPING_READ_FAIL: "여행 중인 TRIP 조회 실패",
  TRIPPED_READ_SUCCESS: "지난 여행 조회 성공",
  TRIPPED_READ_FAIL: "지난 여행 조회 실패",
  TRIP_CREATE_SUCCESS: "여행 예산 짜기 성공",
  TRIP_CREATE_FAIL: "여행 예산 짜기 실패",
  TRIPPING_UPDATE_FAIL: "여행 시작이 실패했습니다",
  TRIPPING_UPDATE_SUCCESS: "여행이 시작되었습니다",
  TRIPPED_UPDATE_FAIL: "여행 종료가 실패했습니다",
  TRIPPED_UPDATE_SUCCESS: "여행이 종료되었습니다",
  TRIP_DELETE_FAIL: "여행 삭제가 실패하였습니다",
  TRIP_DELETE_SUCCESS: "여행이 삭제되었습니다",
  TRIP_EMPTY: "여행에 대한 정보가 없습니다",
  ALREADY_TRIP: "이미 있는 여행 이름입니다",
  ALREADY_TRIPPING: "이미 여행 중입니다",

  /* TripActivity */
  TRIPACTIVITY_READ_SUCCESS: "여행 중 즐길 액티비티들을 조회했습니다.",
  TRIPACTIVITY_READ_FAIL: "액티비티 조회에 실패했습니다.",
  TRIPACTIVITY_CREATE_SUCCESS: "여행 중 즐길 액티비티들을 저장했습니다.",
  TRIPACTIVITY_CREATE_FAIL: "액티비티 저장에 실패했습니다.",
  TRIPACTIVITY_UPDATE_SUCCESS: "여행 중 즐길 액티비티들을 변경했습니다.",
  TRIPACTIVITY_UPDATE_FAIL: "액티비티 변경에 실패했습니다.",
  TRIPACTIVITY_DELETE_SUCCESS: "여행 중 즐길 액티비티를 삭제했습니다.",
  TRIPACTIVITY_DELETE_FAIL: "액티비티 삭제에 실패했습니다.", 
  TRIPACTIVITY_EMPTY: "정보가 없습니다.",

  /* TripHotel */
  TRIPHOTEL_READ_SUCCESS: "여행 중 묵을 숙박들을 조회했습니다.",
  TRIPHOTEL_READ_FAIL: "숙박 조회에 실패했습니다.",
  TRIPHOTEL_CREATE_SUCCESS: "여행 중 묵을 숙박들을 저장했습니다.",
  TRIPHOTEL_CREATE_FAIL: "숙박 저장에 실패했습니다.",
  TRIPHOTEL_UPDATE_SUCCESS: "여행 중 묵을 숙박들을 변경했습니다.",
  TRIPHOTEL_UPDATE_FAIL: "숙박 변경에 실패했습니다.",
  TRIPHOTEL_DELETE_SUCCESS: "여행 중 묵을 숙박을 삭제했습니다.",
  TRIPHOTEL_DELETE_FAIL: "숙박 삭제에 실패했습니다.", 
  TRIPHOTEL_EMPTY: "정보가 없습니다.",
  
  /* TripFood */
  TRIPFOOD_READ_SUCCESS: "여행 중 먹을 식사들을 조회했습니다.",
  TRIPFOOD_READ_FAIL: "식사 조회에 실패했습니다.",
  TRIPFOOD_CREATE_SUCCESS: "여행 중 먹을 식사들을 저장했습니다.",
  TRIPFOOD_CREATE_FAIL: "식사 저장에 실패했습니다.",
  TRIPFOOD_UPDATE_SUCCESS: "여행 중 먹을 식사들을 변경했습니다.",
  TRIPFOOD_UPDATE_FAIL: "식사 변경에 실패했습니다.",
  TRIPFOOD_DELETE_SUCCESS: "여행 중 먹을 식사들을 삭제했습니다.",
  TRIPFOOD_DELETE_FAIL: "식사 삭제에 실패했습니다.",
  TRIPFOOD_EMPTY: "정보가 없습니다.",
  
  /* TripSnack */
  TRIPSNACK_READ_SUCCESS: "여행 중 먹을 간식들을 조회했습니다.",
  TRIPSNACK_READ_FAIL: "간식 조회에 실패했습니다.",
  TRIPSNACK_CREATE_SUCCESS: "여행 중 먹을 간식들을 저장했습니다.",
  TRIPSNACK_CREATE_FAIL: "간식 저장에 실패했습니다.",
  TRIPSNACK_UPDATE_SUCCESS: "여행 중 먹을 간식들을 변경했습니다.",
  TRIPSNACK_UPDATE_FAIL: "간식 변경에 실패했습니다.",
  TRIPSNACK_DELETE_SUCCESS: "여행 중 먹을 간식들을 삭제했습니다.",
  TRIPSNACK_DELETE_FAIL: "간식 삭제에 실패했습니다.",
  TRIPSNACK_EMPTY: "정보가 없습니다.",

  /* User */
  ALREADY_EMAIL: "이미 있는 이메일입니다",
  JOIN_SUCCESS: "회원가입 성공",
  JOIN_FAIL: "회원가입 실패",
  LOGIN_SUCCESS: "로그인 성공",
  MISS_MATCH_PASSWORD: "비밀번호가 일치하지 않습니다.",
  PASSWORD_ENCRYPTION_FAIL: "비밀번호 암호화에 실패하셨습니다",
  NO_EMAIL: "존재하지 않은 아이디입니다",

};